# Generated by Django 3.2.8 on 2021-10-29 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('race_type', models.CharField(choices=[('marathon', 'Marathon'), ('half-marathon', 'Half Marathon'), ('mile', '1600m'), ('800m', '800m'), ('5k', '5k')], default='5k', max_length=100)),
                ('goal', models.TimeField(null=True)),
                ('complete', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['complete'],
            },
        ),
    ]
